[package]
name = "pygmab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "gmab"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.4"
gmab-core = { workspace = true }
